// Auto-generated by OpenLane
module SPI_Master_With_Multi_CS(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input i_Rst_L,
  input i_Clk,
  input[1:0] i_TX_Count,
  input[7:0] i_TX_Byte,
  input i_TX_DV,
  input[1:0] i_Slave_Select,
  output o_TX_Ready,
  output[1:0] o_RX_Count,
  output o_RX_DV,
  output[7:0] o_RX_Byte,
  output o_SPI_Clk,
  input i_SPI_MISO,
  output o_SPI_MOSI,
  output[3:0] o_SPI_CS
);
endmodule
